//! Cross-platform parity: the Rust core must reproduce the TS core's vectors byte-for-byte.
//! Vectors are generated by `packages/arc-crypto/scripts/gen-vectors.mjs`.

use arc_vault_crypto::*;
use serde_json::Value;
use std::fs;

fn vectors() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../vectors/kat.json");
    serde_json::from_str(&fs::read_to_string(path).expect("read kat.json")).expect("parse kat.json")
}

fn hx(s: &str) -> Vec<u8> {
    hex::decode(s).unwrap()
}
fn a32(s: &str) -> [u8; 32] {
    hx(s).try_into().unwrap()
}
fn a24(s: &str) -> [u8; 24] {
    hx(s).try_into().unwrap()
}
fn a64(s: &str) -> [u8; 64] {
    hx(s).try_into().unwrap()
}

#[test]
fn argon2id_matches_ts() {
    let v = vectors();
    let a = &v["argon2id"];
    let out = argon2id(
        &hx(a["passwordHex"].as_str().unwrap()),
        &hx(a["saltHex"].as_str().unwrap()),
        a["m"].as_u64().unwrap() as u32,
        a["t"].as_u64().unwrap() as u32,
        a["p"].as_u64().unwrap() as u32,
        a["dkLen"].as_u64().unwrap() as usize,
    );
    assert_eq!(hex::encode(out), a["outHex"].as_str().unwrap());
}

#[test]
fn hkdf_split_matches_ts() {
    let v = vectors();
    let h = &v["hkdfSplit"];
    let split = split_master_key(&hx(h["ikmHex"].as_str().unwrap()));
    assert_eq!(hex::encode(split.auth_seed), h["authSeedHex"].as_str().unwrap());
    assert_eq!(hex::encode(split.wk), h["wkHex"].as_str().unwrap());
}

#[test]
fn aad_matches_ts() {
    let v = vectors();
    let fields: Vec<(String, String)> = v["aad"]["fields"]
        .as_array()
        .unwrap()
        .iter()
        .map(|f| {
            (
                f[0].as_str().unwrap().to_string(),
                f[1].as_str().unwrap().to_string(),
            )
        })
        .collect();
    let refs: Vec<(&str, &str)> = fields.iter().map(|(a, b)| (a.as_str(), b.as_str())).collect();
    assert_eq!(build_aad(&refs), v["aad"]["out"].as_str().unwrap());
}

#[test]
fn jcs_matches_ts() {
    let v = vectors();
    for case in v["jcs"].as_array().unwrap() {
        assert_eq!(jcs(&case["value"]), case["out"].as_str().unwrap());
    }
}

#[test]
fn aead_matches_ts_and_round_trips() {
    let v = vectors();
    let a = &v["aead"];
    let key = a32(a["keyHex"].as_str().unwrap());
    let nonce = a24(a["nonceHex"].as_str().unwrap());
    let aad = a["aad"].as_str().unwrap().as_bytes();
    let plaintext = hx(a["plaintextHex"].as_str().unwrap());

    let ct = aead_encrypt(&key, &nonce, &plaintext, aad);
    assert_eq!(hex::encode(&ct), a["ciphertextHex"].as_str().unwrap());

    // decrypt the TS-produced ciphertext
    let ts_ct = hx(a["ciphertextHex"].as_str().unwrap());
    assert_eq!(aead_decrypt(&key, &nonce, &ts_ct, aad).unwrap(), plaintext);

    // tamper / wrong-AAD must fail closed
    assert!(aead_decrypt(&key, &nonce, &ts_ct, b"different-aad").is_err());
}

#[test]
fn ed25519_matches_ts() {
    let v = vectors();
    let e = &v["ed25519"];
    let priv32 = a32(e["privHex"].as_str().unwrap());
    let msg = hx(e["messageHex"].as_str().unwrap());

    assert_eq!(hex::encode(ed25519_public(&priv32)), e["pubHex"].as_str().unwrap());
    assert_eq!(hex::encode(ed25519_sign(&priv32, &msg)), e["sigHex"].as_str().unwrap());

    let pub32 = a32(e["pubHex"].as_str().unwrap());
    let sig = a64(e["sigHex"].as_str().unwrap());
    assert!(ed25519_verify(&pub32, &msg, &sig));
    assert!(!ed25519_verify(&pub32, b"tampered", &sig));
}

#[test]
fn opens_a_ts_produced_envelope() {
    let v = vectors();
    let e = &v["aeadEnvelope"];
    let key = a32(e["keyHex"].as_str().unwrap());
    let aad = e["aad"].as_str().unwrap();
    let env: Envelope = serde_json::from_value(e["envelope"].clone()).unwrap();
    let pt = aead_open_envelope(&key, &env, aad).unwrap();
    assert_eq!(hex::encode(pt), e["plaintextHex"].as_str().unwrap());
    // wrong AAD fails closed
    assert!(aead_open_envelope(&key, &env, "different").is_err());
}

#[test]
fn item_encrypt_decrypt_round_trips() {
    let vek = random32();
    let plaintext = br#"{"type":"secret","key":"API_KEY","value":"sk-live"}"#;
    let item = encrypt_item(&vek, "v1", "i1", 1, 1, plaintext);
    let out = decrypt_item(&vek, "v1", "i1", 1, 1, &item.ciphertext, &item.wrapped_item_key).unwrap();
    assert_eq!(out, plaintext);
    // a wrong VEK cannot open the wrapped IK
    assert!(decrypt_item(&random32(), "v1", "i1", 1, 1, &item.ciphertext, &item.wrapped_item_key).is_err());
}

#[test]
fn seal_envelope_round_trips() {
    let (rpriv, rpub) = x25519_keypair();
    let env = seal_to_envelope(&rpub, b"vault-key");
    assert_eq!(seal_open_envelope(&rpriv, &rpub, &env).unwrap(), b"vault-key");
}

#[test]
fn seal_round_trips_and_rejects_wrong_recipient() {
    let (rpriv, rpub) = x25519_keypair();
    let sealed = seal(&rpub, b"vault-key");
    assert_eq!(
        seal_open(&rpriv, &rpub, &sealed.eph_pub, &sealed.nonce, &sealed.ct).unwrap(),
        b"vault-key",
    );
    let (wrong_priv, _) = x25519_keypair();
    assert!(seal_open(&wrong_priv, &rpub, &sealed.eph_pub, &sealed.nonce, &sealed.ct).is_err());
}

#[test]
fn pq_seal_opens_a_ts_produced_envelope() {
    // The core ADR-002 parity check: the TS core seals a known plaintext to a known hybrid
    // identity, and the Rust core unwraps it byte-for-byte. Once decapsulate+HKDF agrees
    // across both stacks, the entire X-Wing combiner (binding salt + AEAD key) does too.
    let v = vectors();
    let p = &v["pqSeal"];
    let mlkem_priv_vec = hx(p["mlkemPrivHex"].as_str().unwrap());
    let mlkem_priv: [u8; 2400] = mlkem_priv_vec.try_into().expect("mlkem priv length");
    let x25519_priv = a32(p["x25519PrivHex"].as_str().unwrap());

    let env: Envelope = serde_json::from_value(p["envelope"].clone()).unwrap();
    let pt = pq_seal_open_envelope(
        &env,
        HybridPriv {
            x25519: &x25519_priv,
            mlkem: &mlkem_priv,
        },
    )
    .expect("pq-seal open against the TS-produced envelope");
    assert_eq!(hex::encode(&pt), p["plaintextHex"].as_str().unwrap());

    // Tampering the KEM ciphertext changes the derived AEAD key (the kem_ct is bound
    // into the HKDF salt), so the open MUST fail closed.
    let mut tampered = env.clone();
    let mut kc_bytes = base64_urlsafe_decode(tampered.kc.as_ref().unwrap());
    kc_bytes[0] ^= 0xff;
    tampered.kc = Some(base64_urlsafe_encode(&kc_bytes));
    assert!(pq_seal_open_envelope(
        &tampered,
        HybridPriv {
            x25519: &x25519_priv,
            mlkem: &mlkem_priv,
        },
    )
    .is_err());
}

#[test]
fn pq_seal_round_trips_within_rust() {
    // Rust generates a hybrid keypair via the TS-compatible APIs and round-trips a payload.
    // This catches breakage in our own Rust impl that the TS-only parity vector wouldn't:
    // if the Rust seal path produced garbage, the open path could still pass the TS vector
    // (since open only exercises decap+HKDF). The round-trip exercises encaps+HKDF too.
    use ml_kem::{
        kem::{Generate, KeyExport},
        ExpandedKeyEncoding, MlKem768,
    };
    let dk = ml_kem::DecapsulationKey::<MlKem768>::generate();
    let mlkem_pub_array = dk.encapsulation_key().to_bytes();
    #[allow(deprecated)]
    let mlkem_priv_array = dk.to_expanded_bytes();

    let (x25519_priv, x25519_pub) = x25519_keypair();
    let mlkem_pub: [u8; 1184] = mlkem_pub_array.as_slice().try_into().unwrap();
    let mlkem_priv: [u8; 2400] = mlkem_priv_array.as_slice().try_into().unwrap();

    let env = pq_seal_to_envelope(
        HybridPub {
            x25519: &x25519_pub,
            mlkem: &mlkem_pub,
        },
        b"a-known-secret",
        "vault/x#kv1",
    );
    let opened = pq_seal_open_envelope(
        &env,
        HybridPriv {
            x25519: &x25519_priv,
            mlkem: &mlkem_priv,
        },
    )
    .expect("round-trip open");
    assert_eq!(opened, b"a-known-secret");
}

// --- small base64url helpers for the tampering check above ---
fn base64_urlsafe_decode(s: &str) -> Vec<u8> {
    use base64::engine::general_purpose::URL_SAFE_NO_PAD;
    use base64::Engine as _;
    URL_SAFE_NO_PAD.decode(s).unwrap()
}
fn base64_urlsafe_encode(b: &[u8]) -> String {
    use base64::engine::general_purpose::URL_SAFE_NO_PAD;
    use base64::Engine as _;
    URL_SAFE_NO_PAD.encode(b)
}
