//! Cross-platform parity: the Rust core must reproduce the TS core's vectors byte-for-byte.
//! Vectors are generated by `packages/vault-crypto/scripts/gen-vectors.mjs`.

use arc_vault_crypto::*;
use serde_json::Value;
use std::fs;

fn vectors() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../vectors/kat.json");
    serde_json::from_str(&fs::read_to_string(path).expect("read kat.json")).expect("parse kat.json")
}

fn hx(s: &str) -> Vec<u8> {
    hex::decode(s).unwrap()
}
fn a32(s: &str) -> [u8; 32] {
    hx(s).try_into().unwrap()
}
fn a24(s: &str) -> [u8; 24] {
    hx(s).try_into().unwrap()
}
fn a64(s: &str) -> [u8; 64] {
    hx(s).try_into().unwrap()
}

#[test]
fn argon2id_matches_ts() {
    let v = vectors();
    let a = &v["argon2id"];
    let out = argon2id(
        &hx(a["passwordHex"].as_str().unwrap()),
        &hx(a["saltHex"].as_str().unwrap()),
        a["m"].as_u64().unwrap() as u32,
        a["t"].as_u64().unwrap() as u32,
        a["p"].as_u64().unwrap() as u32,
        a["dkLen"].as_u64().unwrap() as usize,
    );
    assert_eq!(hex::encode(out), a["outHex"].as_str().unwrap());
}

#[test]
fn hkdf_split_matches_ts() {
    let v = vectors();
    let h = &v["hkdfSplit"];
    let split = split_master_key(&hx(h["ikmHex"].as_str().unwrap()));
    assert_eq!(hex::encode(split.auth_seed), h["authSeedHex"].as_str().unwrap());
    assert_eq!(hex::encode(split.wk), h["wkHex"].as_str().unwrap());
}

#[test]
fn aad_matches_ts() {
    let v = vectors();
    let fields: Vec<(String, String)> = v["aad"]["fields"]
        .as_array()
        .unwrap()
        .iter()
        .map(|f| {
            (
                f[0].as_str().unwrap().to_string(),
                f[1].as_str().unwrap().to_string(),
            )
        })
        .collect();
    let refs: Vec<(&str, &str)> = fields.iter().map(|(a, b)| (a.as_str(), b.as_str())).collect();
    assert_eq!(build_aad(&refs), v["aad"]["out"].as_str().unwrap());
}

#[test]
fn jcs_matches_ts() {
    let v = vectors();
    for case in v["jcs"].as_array().unwrap() {
        assert_eq!(jcs(&case["value"]), case["out"].as_str().unwrap());
    }
}

#[test]
fn aead_matches_ts_and_round_trips() {
    let v = vectors();
    let a = &v["aead"];
    let key = a32(a["keyHex"].as_str().unwrap());
    let nonce = a24(a["nonceHex"].as_str().unwrap());
    let aad = a["aad"].as_str().unwrap().as_bytes();
    let plaintext = hx(a["plaintextHex"].as_str().unwrap());

    let ct = aead_encrypt(&key, &nonce, &plaintext, aad);
    assert_eq!(hex::encode(&ct), a["ciphertextHex"].as_str().unwrap());

    // decrypt the TS-produced ciphertext
    let ts_ct = hx(a["ciphertextHex"].as_str().unwrap());
    assert_eq!(aead_decrypt(&key, &nonce, &ts_ct, aad).unwrap(), plaintext);

    // tamper / wrong-AAD must fail closed
    assert!(aead_decrypt(&key, &nonce, &ts_ct, b"different-aad").is_err());
}

#[test]
fn ed25519_matches_ts() {
    let v = vectors();
    let e = &v["ed25519"];
    let priv32 = a32(e["privHex"].as_str().unwrap());
    let msg = hx(e["messageHex"].as_str().unwrap());

    assert_eq!(hex::encode(ed25519_public(&priv32)), e["pubHex"].as_str().unwrap());
    assert_eq!(hex::encode(ed25519_sign(&priv32, &msg)), e["sigHex"].as_str().unwrap());

    let pub32 = a32(e["pubHex"].as_str().unwrap());
    let sig = a64(e["sigHex"].as_str().unwrap());
    assert!(ed25519_verify(&pub32, &msg, &sig));
    assert!(!ed25519_verify(&pub32, b"tampered", &sig));
}

#[test]
fn opens_a_ts_produced_envelope() {
    let v = vectors();
    let e = &v["aeadEnvelope"];
    let key = a32(e["keyHex"].as_str().unwrap());
    let aad = e["aad"].as_str().unwrap();
    let env: Envelope = serde_json::from_value(e["envelope"].clone()).unwrap();
    let pt = aead_open_envelope(&key, &env, aad).unwrap();
    assert_eq!(hex::encode(pt), e["plaintextHex"].as_str().unwrap());
    // wrong AAD fails closed
    assert!(aead_open_envelope(&key, &env, "different").is_err());
}

#[test]
fn item_encrypt_decrypt_round_trips() {
    let vek = random32();
    let plaintext = br#"{"type":"secret","key":"API_KEY","value":"sk-live"}"#;
    let item = encrypt_item(&vek, "v1", "i1", 1, 1, plaintext);
    let out = decrypt_item(&vek, "v1", "i1", 1, 1, &item.ciphertext, &item.wrapped_item_key).unwrap();
    assert_eq!(out, plaintext);
    // a wrong VEK cannot open the wrapped IK
    assert!(decrypt_item(&random32(), "v1", "i1", 1, 1, &item.ciphertext, &item.wrapped_item_key).is_err());
}

#[test]
fn seal_envelope_round_trips() {
    let (rpriv, rpub) = x25519_keypair();
    let env = seal_to_envelope(&rpub, b"vault-key");
    assert_eq!(seal_open_envelope(&rpriv, &rpub, &env).unwrap(), b"vault-key");
}

#[test]
fn seal_round_trips_and_rejects_wrong_recipient() {
    let (rpriv, rpub) = x25519_keypair();
    let sealed = seal(&rpub, b"vault-key");
    assert_eq!(
        seal_open(&rpriv, &rpub, &sealed.eph_pub, &sealed.nonce, &sealed.ct).unwrap(),
        b"vault-key",
    );
    let (wrong_priv, _) = x25519_keypair();
    assert!(seal_open(&wrong_priv, &rpub, &sealed.eph_pub, &sealed.nonce, &sealed.ct).is_err());
}
