/**
 * SDK-level e2e for passkey unlock. Drives `client.registerPasskey` + `unlockWithPasskey`
 * against the real server using a self-contained `FakeAuthenticator` (real ES256 keypair,
 * real CBOR attestation, real signed assertions, PRF output generated by the
 * authenticator from the salt the server returns). End-to-end proof:
 *
 *   client A (master-password unlock) → registerPasskey
 *   → client B (no prior session) → unlockWithPasskey
 *   → B can read items A put → B can write items (signing priv unwrapped too)
 */
import { type INestApplication, ValidationPipe } from "@nestjs/common";
import { Test } from "@nestjs/testing";
import { type AddressInfo } from "node:net";
import { VaultClient, type PasskeyAuthenticator } from "@arc/sdk";
import {
  createHash,
  createSign,
  generateKeyPairSync,
  hkdfSync,
  randomBytes,
  type KeyObject,
} from "node:crypto";
import { AppModule } from "../src/app.module";

const RP_ID = "localhost";
const ORIGIN = "http://localhost:5173";

// -- CBOR helpers (subset we emit) ------------------------------------------------------

function cborUint(n: number): Buffer {
  if (n < 24) return Buffer.from([n]);
  if (n < 256) return Buffer.from([24, n]);
  if (n < 65536) return Buffer.from([25, (n >> 8) & 0xff, n & 0xff]);
  throw new Error("cborUint out of range");
}
function cborNegInt(value: number): Buffer {
  const n = -1 - value;
  if (n < 24) return Buffer.from([0x20 | n]);
  if (n < 256) return Buffer.from([0x38, n]);
  throw new Error("cborNegInt out of range");
}
function cborBytes(b: Uint8Array): Buffer {
  const len = b.length;
  let header: Buffer;
  if (len < 24) header = Buffer.from([0x40 | len]);
  else if (len < 256) header = Buffer.from([0x58, len]);
  else if (len < 65536) header = Buffer.from([0x59, (len >> 8) & 0xff, len & 0xff]);
  else throw new Error("cborBytes out of range");
  return Buffer.concat([header, Buffer.from(b)]);
}
function cborText(s: string): Buffer {
  const b = Buffer.from(s, "utf8");
  if (b.length < 24) return Buffer.concat([Buffer.from([0x60 | b.length]), b]);
  return Buffer.concat([Buffer.from([0x78, b.length]), b]);
}
function cborMap(entries: Array<[Buffer, Buffer]>): Buffer {
  const header = 0xa0 | entries.length;
  return Buffer.concat([Buffer.from([header]), ...entries.flat()]);
}
function b64url(b: Buffer | Uint8Array): string {
  return Buffer.from(b).toString("base64url");
}

// -- Fake authenticator implementing the PasskeyAuthenticator interface -----------------

/**
 * Real ES256 P-256 keypair + real signatures + a per-credential secret used as the PRF
 * source. The PRF output is `HKDF-SHA256(secret, salt=prfFirst, info="prf")` so register
 * + unlock produce the same 32-byte output for the same salt — matches what a real
 * WebAuthn PRF extension does on real authenticators.
 */
function makeAuthenticator(): PasskeyAuthenticator {
  const credentialId = randomBytes(32);
  const kp = generateKeyPairSync("ec", { namedCurve: "P-256" });
  const privateKey: KeyObject = kp.privateKey;
  const spki = kp.publicKey.export({ type: "spki", format: "der" }) as Buffer;
  const pubKeyRaw = spki.subarray(spki.length - 65);
  const prfSecret = randomBytes(32);
  let signCount = 0;

  const prf = (salt: Uint8Array): Uint8Array =>
    new Uint8Array(hkdfSync("sha256", prfSecret, salt, "prf", 32));

  return {
    async create(opts) {
      const clientDataJSON = Buffer.from(
        JSON.stringify({ type: "webauthn.create", challenge: opts.challenge, origin: ORIGIN, crossOrigin: false }),
        "utf8",
      );
      const rpIdHash = createHash("sha256").update(RP_ID).digest();
      const flags = 0x01 | 0x04 | 0x40;
      const counter = Buffer.alloc(4);
      const credIdLen = Buffer.alloc(2);
      credIdLen.writeUInt16BE(credentialId.length, 0);
      const x = pubKeyRaw.subarray(1, 33);
      const y = pubKeyRaw.subarray(33, 65);
      const coseKey = cborMap([
        [cborUint(1), cborUint(2)],
        [cborUint(3), cborNegInt(-7)],
        [cborNegInt(-1), cborUint(1)],
        [cborNegInt(-2), cborBytes(x)],
        [cborNegInt(-3), cborBytes(y)],
      ]);
      const authData = Buffer.concat([
        rpIdHash,
        Buffer.from([flags]),
        counter,
        Buffer.alloc(16),
        credIdLen,
        credentialId,
        coseKey,
      ]);
      const attestationObject = cborMap([
        [cborText("fmt"), cborText("none")],
        [cborText("attStmt"), cborMap([])],
        [cborText("authData"), cborBytes(authData)],
      ]);
      return {
        attestation: {
          id: b64url(credentialId),
          rawId: b64url(credentialId),
          type: "public-key",
          response: {
            attestationObject: b64url(attestationObject),
            clientDataJSON: b64url(clientDataJSON),
          },
          clientExtensionResults: {},
        },
        prfOutput: prf(opts.prfFirst),
      };
    },
    async get(opts) {
      const clientDataJSON = Buffer.from(
        JSON.stringify({ type: "webauthn.get", challenge: opts.challenge, origin: ORIGIN, crossOrigin: false }),
        "utf8",
      );
      const rpIdHash = createHash("sha256").update(RP_ID).digest();
      const flags = 0x01 | 0x04;
      signCount += 1;
      const counter = Buffer.alloc(4);
      counter.writeUInt32BE(signCount, 0);
      const authenticatorData = Buffer.concat([rpIdHash, Buffer.from([flags]), counter]);
      const clientDataHash = createHash("sha256").update(clientDataJSON).digest();
      const signer = createSign("sha256");
      signer.update(Buffer.concat([authenticatorData, clientDataHash]));
      signer.end();
      const signature = signer.sign(privateKey);
      return {
        assertion: {
          id: b64url(credentialId),
          rawId: b64url(credentialId),
          type: "public-key",
          response: {
            authenticatorData: b64url(authenticatorData),
            clientDataJSON: b64url(clientDataJSON),
            signature: b64url(signature),
          },
          clientExtensionResults: {},
        },
        prfOutput: prf(opts.prfFirst),
      };
    },
  };
}

describe("SDK passkey e2e (register then unlock-with-passkey produces a full-capability session)", () => {
  let app: INestApplication;
  let baseUrl: string;

  beforeAll(async () => {
    const saved = { rp: process.env.ARC_PASSKEY_RP_ID, origin: process.env.ARC_PASSKEY_ORIGIN };
    process.env.ARC_PASSKEY_RP_ID = RP_ID;
    process.env.ARC_PASSKEY_ORIGIN = ORIGIN;
    try {
      const mod = await Test.createTestingModule({ imports: [AppModule] }).compile();
      app = mod.createNestApplication();
      app.useGlobalPipes(new ValidationPipe({ transform: true, whitelist: true }));
      await app.listen(0);
      const addr = app.getHttpServer().address() as AddressInfo;
      baseUrl = `http://127.0.0.1:${addr.port}`;
    } finally {
      if (saved.rp === undefined) delete process.env.ARC_PASSKEY_RP_ID;
      else process.env.ARC_PASSKEY_RP_ID = saved.rp;
      if (saved.origin === undefined) delete process.env.ARC_PASSKEY_ORIGIN;
      else process.env.ARC_PASSKEY_ORIGIN = saved.origin;
    }
  });

  afterAll(async () => {
    await app.close();
  });

  it("registers a passkey, then unlocks a fresh client with it and round-trips a write", async () => {
    const authenticator = makeAuthenticator();

    // Session A: master-password unlock + register a passkey.
    const A = new VaultClient({ baseUrl, profile: "test" });
    await A.devLogin("passkey-sdk@example.com");
    await A.enroll("master-pw");
    const { credentialId } = await A.registerPasskey(authenticator, "MacBook Touch ID");
    expect(credentialId).toBeTruthy();

    // A also creates a vault + an item so we can prove B can read + write after unlock.
    const vault = await A.createVault("team");
    await A.putItem(
      vault.id,
      { type: "secret", key: "K", value: "v-from-A" },
      { type: "secret" },
    );

    const list = await A.listPasskeys();
    expect(list).toHaveLength(1);
    expect(list[0]!.label).toBe("MacBook Touch ID");

    // Session B: fresh client, no prior session — unlock via passkey only.
    const B = new VaultClient({ baseUrl, profile: "test" });
    await B.devLogin("passkey-sdk@example.com");
    await B.unlockWithPasskey(authenticator);

    // B can read items A wrote (identity priv unwrapped).
    await B.listVaults();
    const pulled = await B.pull(vault.id, 0);
    expect(pulled.items[0]!.data).toMatchObject({ key: "K", value: "v-from-A" });

    // B can also write — signing priv was unwrapped too, so a vault-head update works.
    await B.putItem(
      vault.id,
      { type: "secret", key: "K2", value: "v-from-B" },
      { type: "secret" },
    );

    // A re-reads and sees B's write (after listVaults to refresh cache).
    const A2 = new VaultClient({ baseUrl, profile: "test" });
    await A2.devLogin("passkey-sdk@example.com");
    await A2.unlock("master-pw");
    await A2.listVaults();
    const reread = await A2.pull(vault.id, 0);
    const keys = reread.items.map((i) => (i.data as { key: string }).key);
    expect(keys).toEqual(expect.arrayContaining(["K", "K2"]));
  });

  it("removePasskey deletes the credential — subsequent unlock fails", async () => {
    const authenticator = makeAuthenticator();
    const A = new VaultClient({ baseUrl, profile: "test" });
    await A.devLogin("passkey-rm@example.com");
    await A.enroll("master-pw");
    await A.registerPasskey(authenticator);
    const [registered] = await A.listPasskeys();
    expect(registered).toBeTruthy();

    await A.removePasskey(registered!.id);
    expect(await A.listPasskeys()).toEqual([]);

    const B = new VaultClient({ baseUrl, profile: "test" });
    await B.devLogin("passkey-rm@example.com");
    // No credentials → unlock-challenge 404s before the authenticator is invoked.
    await expect(B.unlockWithPasskey(authenticator)).rejects.toThrow();
  });
});
